### ISSUE TITLE
Problem running read_from_device.py

### ISSUE THREAD

**Issue by darkopetrovic** [jpaalasm/zephyr-bt#1]
Hi,

I've just tried your script read_from_device.py with my Zephyr Bioharness 3.0 and Python 2.7 and I've got this error:

<pre>
Traceback (most recent call last):
  File "...\eclipse\plugins\org.python.pydev_2.7.1.2012100913\pysrc\pydevd.py", line 1397, in <module>
    debugger.run(setup['file'], None, None)
  File "...\eclipse\plugins\org.python.pydev_2.7.1.2012100913\pysrc\pydevd.py", line 1090, in run
    pydev_imports.execfile(file, globals, locals) #execute the script
  File "...\zephyr-bt\testing\read_from_device.py", line 25, in <module>
    main()
  File "...\zephyr-bt\testing\read_from_device.py", line 21, in main
    simulation_workflow([callback], ser)
  File "...\zephyr-bt\src\zephyr\testing.py", line 145, in simulation_workflow
    protocol.run()
  File "...\zephyr-bt\src\zephyr\protocol.py", line 93, in run
    self.read_and_handle_byte()
  File "...\zephyr-bt\src\zephyr\protocol.py", line 81, in read_and_handle_byte
    for callback in self.callbacks:
TypeError: 'instancemethod' object is not iterable
</pre>

I hope we can find a solution for this.

**Comment by jpaalasm** [comment]
Thanks for the report!

There was s a simple bug in the testing code. It's now fixed.

**Comment by darkopetrovic** [comment]
Yes! it works. Thanks.
